backout of commit 8594a5210dc3173f8bcd2bae8f52f91c5ca7221d
Turns out the container is problematic too.
setup-bun action failed with:

```
Error: Error: Unable to locate executable file: unzip. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```